data_dir: '/datasets01/COCO/022719'
lab_dir: '/datasets01/COCO-Stuff/072318'
caption_dir: '/datasets01/COCO/022719/annotations'
size: 512
model.__class__: src.zestguide_stbl14.GradientGuidedSynthesis2
model.num_inference_steps: 50
model.guidance_scale: 7.5
model.tau: 0.5
model.lr: 0.3
model.temp: 1
model.loss_scaler: 10
model.loss_ls: 0.1
model.lr_schedule: True
model.use_32_blocks: True
model.ddim_eta: 0.5
model.ediffi_coeff: 5.0
model.negative_mode: concat
model.loss: zestguide_utils.bce_loss2
model.grad_norm: l0
model.clip_init: False
model.average_maps_layerwise: True
